linters:
  enable:
    - errcheck      # Check error returns
    - govet         # Go vet checks
    - staticcheck   # Advanced static analysis
    - unused        # Find unused code
    - gosimple      # Simplification suggestions
    - ineffassign   # Detect ineffectual assignments
    - gocritic      # Opinionated style checks
    - revive        # Replacement for golint

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: exported
        severity: warning

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
