# GoReleaser configuration for auxot
# Triggered by: git tag v0.1.0 && git push --tags
# Docs: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - make sync-registry

builds:
  - id: auxot-router
    main: ./cmd/auxot-router
    binary: auxot-router
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}

  - id: auxot-worker
    main: ./cmd/auxot-worker
    binary: auxot-worker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}

  - id: auxot-tools
    main: ./cmd/auxot-tools
    binary: auxot-tools
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # Package router + worker into one archive per platform
    builds:
      - auxot-router
      - auxot-worker

  - id: tools
    format: tar.gz
    name_template: "{{ .ProjectName }}_tools_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # Separate archive for auxot-tools (includes Windows)
    builds:
      - auxot-tools

brews:
  - name: auxot-worker
    # Use the default archive (contains auxot-router + auxot-worker).
    # Only auxot-worker is installed; the formula is published to homebrew-tap.
    ids:
      - default
    repository:
      owner: auxothq
      name: homebrew-tap
      branch: main
      # Set HOMEBREW_TAP_GITHUB_TOKEN in the release CI environment.
      # A fine-grained PAT with Contents: write on auxothq/homebrew-tap is sufficient.
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "chore: update auxot-worker formula to {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/auxothq/auxot"
    description: "GPU inference worker for the Auxot platform"
    license: "MIT"
    caveats: |
      To connect immediately (foreground):
        auxot-worker --gpu-key <key>

      To install as a persistent daemon (starts on boot):
        auxot-worker install --name default --gpu-key <key>
        sudo auxot-worker install --name default --gpu-key <key> --always-on

      Manage installed workers:
        auxot-worker list
        auxot-worker uninstall <name>
    install: |
      bin.install "auxot-worker"
    test: |
      output = shell_output("#{bin}/auxot-worker version")
      assert_match "auxot-worker", output

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

release:
  github:
    owner: auxothq
    name: auxot
  prerelease: auto
  name_template: "v{{.Version}}"
